[Application]

APP_ENV = dev
app_name = deca-demo
APP_DEBUG = true
display_errors = true

; For Symfony Mailer
MAILER_DSN = null://null

; For PHPMailer
PHP_MAILER_HOST = null
PHP_MAILER_USERNAME =
PHP_MAILER_PASSWORD =
